### PR TITLE
AGFMA dataset JSON output

### LINKED ISSUE #75: Ingest study and biosamples for GOLD study Gs0118397 (AGFMA)
We need to ingest the study and biosample data from GOLD for Gs0118397 similar to what we did for bioscales and grow. We only want a subset of the metatranscriptome projects. GOLD has populated the environmental terms.

There are two options to handle selecting only a subset of the projects. This first is manual, use the [spreadsheet](https://docs.google.com/spreadsheets/d/1kp3bQmdkOCFaKyAoDOHyXI3dfkNFP8datfgPlgfMtM8/edit#gid=1398928692) where I've prefiltered the data, use the "GOLD biosamples include" and "GOLD bioprojects include". The second is the values of "itsSequencingProductName" to filter the results. Reddy says this information is in the NMDC endpoint. For this project we only want projects that match 'Metagenome Standard Draft' or 'Eukaryote Community Metatranscriptome'. There should be 95 biosamples.
Example of a metatranscriptome project to include Gb0237200
Example of a metatranscriptome project to exclude Gp0401539

Note all the projects are host-associated so should have a host tax id and host tax name similar to some of the Bioscales samples.

### PR DESCRIPTION
**Pull request by sujaypatil96**
JSON output generated from the GOLD NMDC dataset transformation pipeline for the AGFMA dataset.

Fixes https://github.com/microbiomedata/issues/issues/75

### CODE REVIEW

**Comment by sujaypatil96** [comment]
This seeks to fix https://github.com/microbiomedata/issues/issues/75

**Comment by sujaypatil96** [comment]
Fixes https://github.com/microbiomedata/issues/issues/75

**Review by aclum — CHANGES_REQUESTED** [review]
Same here, collected_from populated with a FieldResearchSite identifier needs to be removed.

**Review by aclum — CHANGES_REQUESTED** [review]
Please update img_identifiers to a curie.  ex `3300047319` should be come `img.taxon:3300047319`

**Review by aclum — APPROVED** [review]

**Pull request merged**
